// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umuna.ApiServer.Data;

#nullable disable

namespace Umuna.ApiServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251109160350_AddCameraPositionsToUser")]
    partial class AddCameraPositionsToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Umuna.Core.Domain.Data.CameraPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CameraPosition");
                });

            modelBuilder.Entity("Umuna.Core.Domain.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Umuna.Core.Domain.Data.CameraPosition", b =>
                {
                    b.HasOne("Umuna.Core.Domain.Data.User", null)
                        .WithMany("CameraPositions")
                        .HasForeignKey("UserId");

                    b.OwnsOne("Umuna.Core.Domain.Data.QuaternionModel", "Rotation", b1 =>
                        {
                            b1.Property<int>("CameraPositionId")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("W")
                                .HasColumnType("REAL");

                            b1.Property<float>("X")
                                .HasColumnType("REAL");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL");

                            b1.Property<float>("Z")
                                .HasColumnType("REAL");

                            b1.HasKey("CameraPositionId");

                            b1.ToTable("CameraPosition");

                            b1.WithOwner()
                                .HasForeignKey("CameraPositionId");
                        });

                    b.OwnsOne("Umuna.Core.Domain.Data.Vector3Model", "Position", b1 =>
                        {
                            b1.Property<int>("CameraPositionId")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("X")
                                .HasColumnType("REAL");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL");

                            b1.Property<float>("Z")
                                .HasColumnType("REAL");

                            b1.HasKey("CameraPositionId");

                            b1.ToTable("CameraPosition");

                            b1.WithOwner()
                                .HasForeignKey("CameraPositionId");
                        });

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("Rotation")
                        .IsRequired();
                });

            modelBuilder.Entity("Umuna.Core.Domain.Data.User", b =>
                {
                    b.Navigation("CameraPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
